name: Export Docker Image

on:
  workflow_dispatch: # 手动触发

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: docker pull minio/minio:latest
      - name: Save Docker image to tarball
        run: docker save minio/minio:latest > minio.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: minio
          path: minio
          retention-days: 5 # 产物保留天数
