name: Export Docker Image

on:
  workflow_dispatch: # 手动触发

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: docker pull dpage/pgadmin4:9.2.0
      - name: Save Docker image to tarball
        run: docker save dpage/pgadmin4:9.2.0 > pgadmin4.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pgadmin4
          path: pgadmin4.tar
          retention-days: 5 # 产物保留天数
