name: Export Docker Image

on:
  workflow_dispatch: # 手动触发

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: docker pull joxit/docker-registry-ui:main
      - name: Save Docker image to tarball
        run: docker save joxit/docker-registry-ui:main > docker-registry-ui.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-registry-ui
          path: docker-registry-ui.tar
          retention-days: 5 # 产物保留天数
