name: Export Docker Image

on:
  workflow_dispatch: # 手动触发

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: docker pull dexidp/dex:v2.42.0
      - name: Save Docker image to tarball
        run: docker save dexidp/dex:v2.42.0 > dex.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dex
          path: dex.tar
          retention-days: 5 # 产物保留天数
