name: Export Docker Image

on:
  workflow_dispatch: # 手动触发

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: docker pull otel/opentelemetry-collector-contrib:0.138.0

      - name: Save Docker image to tarball
        run: docker save otel/opentelemetry-collector-contrib:0.138.0 > opentelemetry.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: opentelemetry
          path: opentelemetry.tar
          retention-days: 5 # 产物保留天数
